/*--------------ANALYSIS BEGINS-----------------*/

-- ====================================================
-- File: analysis.sql
-- Purpose: Joins, correlations, feature engineering, ML
-- ====================================================

USE DATABASE BARCLAYS_ECON_DB;
USE SCHEMA CLEAN;

-- Verify tables exist
SHOW TABLES LIKE 'ECONOMIC_FACT';
select * from FOREX.MARKET_FINAL;

-- ====================================================
-- 1️⃣ JOIN FOREX + ECONOMIC DATA
-- ====================================================

CREATE OR REPLACE VIEW FOREX.MARKET_ECON_JOINED AS
SELECT
    m.DATE,
    m.MARKET,
    m.OPEN,
    m.HIGH,
    m.LOW,
    m.CLOSE,
    m.ADJ_CLOSE,
    m.VOLUME,
    m.CURRENCY,
    e.GDP_GROWTH,
    e.INFLATION_RATE,
    e.LENDING_INTEREST,
    e.EXCHANGE_RATE
FROM FOREX.MARKET_FINAL m
LEFT JOIN CLEAN.ECONOMIC_FACT e
    ON YEAR(m.DATE) = e.YEAR   -- ✅ now both sides are numbers
ORDER BY m.DATE;

SELECT * FROM FOREX.MARKET_ECON_JOINED;


-- ====================================================
-- 2️⃣ CORRELATION TABLES (INDICATOR vs MARKET)
-- ====================================================

--Core Correlation Table (Market Close vs Economic Indicators)

CREATE OR REPLACE TABLE FOREX.CORRELATION_MARKET_ECON AS
SELECT
    MARKET,

    CORR(CLOSE, GDP_GROWTH)       AS CORR_CLOSE_GDP,
    CORR(CLOSE, INFLATION_RATE)   AS CORR_CLOSE_INFLATION,
    CORR(CLOSE, LENDING_INTEREST) AS CORR_CLOSE_LENDING,
    CORR(CLOSE, EXCHANGE_RATE)    AS CORR_CLOSE_EXCHANGE,

    CORR(VOLUME, GDP_GROWTH)       AS CORR_VOL_GDP,
    CORR(VOLUME, INFLATION_RATE)   AS CORR_VOL_INFLATION,
    CORR(VOLUME, LENDING_INTEREST) AS CORR_VOL_LENDING,
    CORR(VOLUME, EXCHANGE_RATE)    AS CORR_VOL_EXCHANGE

FROM FOREX.MARKET_ECON_JOINED
GROUP BY MARKET;

SELECT * FROM FOREX.CORRELATION_MARKET_ECON

--Year-wise Correlation Trend (how correlation changes over time)

CREATE OR REPLACE TABLE FOREX.CORR_YEARLY AS
SELECT 
    YEAR(DATE) AS YEAR,
    MARKET,

    CORR(CLOSE, GDP_GROWTH) AS CORR_GDP,
    CORR(CLOSE, INFLATION_RATE) AS CORR_INFLATION,
    CORR(CLOSE, EXCHANGE_RATE) AS CORR_FOREX

FROM FOREX.MARKET_ECON_JOINED
GROUP BY YEAR, MARKET
ORDER BY YEAR, MARKET;

SELECT * FROM FOREX.CORR_YEARLY

--Inter-Market Correlation (Market vs Market)

CREATE OR REPLACE TABLE FOREX.CORR_NIFTY_FTSE AS
SELECT
    CORR(a.CLOSE, b.CLOSE) AS CORR_NIFTY_FTSE
FROM (
    SELECT DATE, CLOSE FROM FOREX.MARKET_FINAL WHERE MARKET = 'NIFTY'
) a
JOIN (
    SELECT DATE, CLOSE FROM FOREX.MARKET_FINAL WHERE MARKET = 'FTSE'
) b
ON a.DATE = b.DATE;

SELECT * FROM FOREX.CORR_NIFTY_FTSE

-----------------------------------------------------------------------------

CREATE OR REPLACE TABLE FOREX.CORR_NIFTY_SP500 AS
SELECT
    CORR(a.CLOSE, b.CLOSE) AS CORR_NIFTY_SP500
FROM (
    SELECT DATE, CLOSE FROM FOREX.MARKET_FINAL WHERE MARKET = 'NIFTY'
) a
JOIN (
    SELECT DATE, CLOSE FROM FOREX.MARKET_FINAL WHERE MARKET = 'SP500'
) b
ON a.DATE = b.DATE;

SELECT * FROM FOREX.CORR_NIFTY_SP500

-----------------------------------------------------------------------------

CREATE OR REPLACE TABLE FOREX.CORR_FTSE_SP500 AS
SELECT
    CORR(a.CLOSE, b.CLOSE) AS CORR_FTSE_SP500
FROM (
    SELECT DATE, CLOSE FROM FOREX.MARKET_FINAL WHERE MARKET = 'FTSE'
) a
JOIN (
    SELECT DATE, CLOSE FROM FOREX.MARKET_FINAL WHERE MARKET = 'SP500'
) b
ON a.DATE = b.DATE;

SELECT * FROM FOREX.CORR_FTSE_SP500

-------------------------------------------------------

CREATE OR REPLACE VIEW FOREX.MARKET_COMPARE_FULL AS
SELECT
    DATE,

    -- Close values
    MAX(CASE WHEN MARKET = 'USDINR' THEN CLOSE END) AS USDINR_CLOSE,
    MAX(CASE WHEN MARKET = 'NIFTY'  THEN CLOSE END) AS NIFTY_CLOSE,
    MAX(CASE WHEN MARKET = 'SP500'  THEN CLOSE END) AS SP500_CLOSE,
    MAX(CASE WHEN MARKET = 'FTSE'   THEN CLOSE END) AS FTSE_CLOSE,

    -- Volume values
    MAX(CASE WHEN MARKET = 'USDINR' THEN VOLUME END) AS USDINR_VOL,
    MAX(CASE WHEN MARKET = 'NIFTY'  THEN VOLUME END) AS NIFTY_VOL,
    MAX(CASE WHEN MARKET = 'SP500'  THEN VOLUME END) AS SP500_VOL,
    MAX(CASE WHEN MARKET = 'FTSE'   THEN VOLUME END) AS FTSE_VOL,

    -- Currency
    MAX(CASE WHEN MARKET = 'USDINR' THEN CURRENCY END) AS USDINR_CUR,
    MAX(CASE WHEN MARKET = 'NIFTY'  THEN CURRENCY END) AS NIFTY_CUR,
    MAX(CASE WHEN MARKET = 'SP500'  THEN CURRENCY END) AS SP500_CUR,
    MAX(CASE WHEN MARKET = 'FTSE'   THEN CURRENCY END) AS FTSE_CUR

FROM FOREX.MARKET_FINAL
GROUP BY DATE
ORDER BY DATE;

SELECT * FROM FOREX.MARKET_COMPARE_FULL


CREATE OR REPLACE TABLE CLEAN.DIM_DATE AS
WITH seq AS (
  SELECT DATEADD(
           day,
           ROW_NUMBER() OVER (ORDER BY seq4()) - 1,
           '1960-01-01'::DATE
         ) AS dt
  FROM TABLE(GENERATOR(ROWCOUNT => 30000))   -- generates 30,000 days (covers 1960-2050)
)
SELECT
  dt AS DATE,
  YEAR(dt) AS YEAR,
  MONTH(dt) AS MONTH,
  DAY(dt) AS DAY,
  TO_CHAR(dt, 'MON') AS MONTH_ABBR,
  TO_CHAR(dt, 'YYYY-MM') AS YEAR_MONTH,
  CASE WHEN MONTH(dt) IN (1, 2, 3) THEN 'Q1'
       WHEN MONTH(dt) IN (4, 5, 6) THEN 'Q2'
       WHEN MONTH(dt) IN (7, 8, 9) THEN 'Q3'
       ELSE 'Q4' END AS QUARTER,
  DATE_PART('WEEK', dt) AS WEEK_OF_YEAR,
  IFF(dt = TRUNC(dt, 'MM'), 1, 0) AS IS_MONTH_START
FROM seq
WHERE dt <= CURRENT_DATE();


-- ====================================================
-- ✅ ML DATASET WITH FEATURES
-- Includes: % Change, Volatility, Lag, Moving Average
-- ====================================================

CREATE OR REPLACE TABLE FOREX.ML_MARKET_FEATURES AS
SELECT
    DATE,
    MARKET,
    CLOSE,
    VOLUME,

    -- Daily % change
    (CLOSE - LAG(CLOSE, 1) OVER (PARTITION BY MARKET ORDER BY DATE))
        / NULLIF(LAG(CLOSE, 1) OVER (PARTITION BY MARKET ORDER BY DATE), 0)
        AS DAILY_PCT_CHANGE,

    -- Price volatility (past 7-day window)
    STDDEV(CLOSE) OVER (PARTITION BY MARKET ORDER BY DATE ROWS BETWEEN 7 PRECEDING AND CURRENT ROW)
        AS VOLATILITY_7D,

    -- 7-day lag closing price
    LAG(CLOSE, 7) OVER (PARTITION BY MARKET ORDER BY DATE)
        AS LAG_7D,

    -- 30-day moving average
    AVG(CLOSE) OVER (PARTITION BY MARKET ORDER BY DATE ROWS BETWEEN 30 PRECEDING AND CURRENT ROW)
        AS MA_30D
FROM FOREX.MARKET_FINAL
ORDER BY MARKET, DATE;


CREATE OR REPLACE STAGE ML_EXPORT_STAGE;

COPY INTO @ML_EXPORT_STAGE/ml_dataset
FROM FOREX.ML_MARKET_FEATURES
FILE_FORMAT = (
    TYPE = CSV,
    FIELD_DELIMITER = ',',
    COMPRESSION = GZIP,
    SKIP_HEADER = 0
)
HEADER = TRUE
OVERWRITE = TRUE;

LIST @ML_EXPORT_STAGE;

LIST @ML_EXPORT_STAGE/ml_dataset;












